### ISSUE TITLE
安卓微信

### ISSUE THREAD

**Issue by myqianlan** [ustbhuangyi/time-picker#1]
安卓微信 布局乱了

**Comment by ustbhuangyi** [comment]
请问你的安卓手机是什么机型，最好能附一张布局乱的图

**Comment by myqianlan** [comment]
@ustbhuangyi     华为p6s
![image](https://cloud.githubusercontent.com/assets/5117885/9808047/e5a05e58-588d-11e5-8324-8e7d09afd580.png)

**Comment by ustbhuangyi** [comment]
华为的微信只支持老版的flex box布局，太坑~~我修复了，你看一下效果
