### ISSUE TITLE
遮盖层 显示问题

### ISSUE THREAD

**Issue by twoer** [ustbhuangyi/time-picker#2]
应该在点击选择之后，就出现 遮盖层，
而不是在 选择器 出来之后，再出现 遮盖层，页面突然一黑，比较怪，
或者给 遮盖层 加上 opacity 动画，也会好一点。

机型  ip5 微信，Safari 。

**Comment by ustbhuangyi** [comment]
ios9的bug，已修复

**Comment by ustbhuangyi** [comment]
ios9的bug，已修复
